name = "AutoWrap"
uuid = "b28b87c8-a228-4bfa-a330-38707e5fee2d"
authors = ["Manuel Berkemeier <manuelbb@mail.uni-paderborn.de>"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
